# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PracRxLoginApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PracRxLoginApp
  # RxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'PracRxLoginAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PracRxLoginAppUITests' do
    # Pods for testing
  end

end
